{
    "openapi": "3.0.0",
    "info": {
        "title": "PUC PETS - docs",
        "version": "1.0"
    },
    "paths": {
        "/api/auth/login": {
            "post": {
                "tags": [
                    "authentication"
                ],
                "summary": "make login to get authenticated",
                "operationId": "login",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "email": "test@mail.com",
                                    "password": "test123"
                                }
                            }
                        },
                        "application/x-www-form-urlencoded": {
                            "schema": {
                                "properties": {
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "email": "mail@mail.com",
                                    "password": "1234678"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "401": {
                        "description": "Invalid Credentials"
                    }
                }
            }
        },
        "/api/auth/me": {
            "get": {
                "tags": [
                    "authentication"
                ],
                "summary": "details about signed account as token and user detail",
                "operationId": "authUserDetails",
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/auth/logout": {
            "post": {
                "tags": [
                    "authentication"
                ],
                "summary": "logout and revoke token",
                "operationId": "logout",
                "responses": {
                    "200": {
                        "description": "Successfully logged out"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/auth/refresh": {
            "post": {
                "tags": [
                    "authentication"
                ],
                "summary": "refresh actual token",
                "operationId": "refreshToken",
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/auth/pet": {
            "get": {
                "tags": [
                    "pets"
                ],
                "summary": "list all pets in system",
                "operationId": "listPets",
                "responses": {
                    "200": {
                        "description": "Validation Response"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "pets"
                ],
                "summary": "register pet",
                "operationId": "registerPet",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "size": {
                                        "type": "string"
                                    },
                                    "birth_date": {
                                        "type": "string",
                                        "format": "date"
                                    },
                                    "owner_id": {
                                        "type": "integer"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "name": "Qiyana",
                                    "size": "small",
                                    "birth_date": "2019-01-01",
                                    "owner_id": 1
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/auth/pet/{id}": {
            "get": {
                "tags": [
                    "pets"
                ],
                "summary": "list pet by id",
                "operationId": "listPetById",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "pet id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "204": {
                        "description": "Content not found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "pets"
                ],
                "summary": "update pet",
                "operationId": "updatPet",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "pet id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "size": {
                                        "type": "string"
                                    },
                                    "birth_date": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "name": "Bidu",
                                    "size": "medium",
                                    "birth_date": "2018-01-01"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successfully updated"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "pets"
                ],
                "summary": "remove pet",
                "operationId": "removePet",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "pet id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully deleted"
                    },
                    "204": {
                        "description": "Content not found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/auth/schedule": {
            "get": {
                "tags": [
                    "schedules"
                ],
                "summary": "list all schedules status",
                "operationId": "listSchedules",
                "responses": {
                    "200": {
                        "description": "Validation Response"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "schedules"
                ],
                "summary": "create schedule",
                "operationId": "createSchedule",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "vet_id": {
                                        "type": "integer"
                                    },
                                    "date": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "vet_id": 1,
                                    "date": "01-01-2025 12:00"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "201": {
                        "description": "Success"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/auth/schedule/open": {
            "get": {
                "tags": [
                    "schedules"
                ],
                "summary": "list all open schedules",
                "operationId": "listOpenSchedules",
                "responses": {
                    "200": {
                        "description": "Validation Response"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/auth/schedule/pending": {
            "get": {
                "tags": [
                    "schedules"
                ],
                "summary": "list all pending schedules",
                "operationId": "listPendingSchedules",
                "responses": {
                    "200": {
                        "description": "Validation Response"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/auth/schedule/confirmed": {
            "get": {
                "tags": [
                    "schedules"
                ],
                "summary": "list all confirmed schedules",
                "operationId": "listConfirmedSchedules",
                "responses": {
                    "200": {
                        "description": "Validation Response"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/auth/schedule/canceled": {
            "get": {
                "tags": [
                    "schedules"
                ],
                "summary": "list all canceled schedules",
                "operationId": "listCanceledSchedules",
                "responses": {
                    "200": {
                        "description": "Validation Response"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/auth/schedule/{id}/assign": {
            "post": {
                "tags": [
                    "schedules"
                ],
                "summary": "client assign to a schedule",
                "operationId": "assignSchedule",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "schedule id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "client_id": {
                                        "type": "integer"
                                    },
                                    "pet_id": {
                                        "type": "integer"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "client_id": 12,
                                    "pet_id": 55
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successfully updated"
                    },
                    "204": {
                        "description": "Content not found"
                    },
                    "400": {
                        "description": "This schedule cannot be assigned as its status is no longer open"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/auth/schedule/{id}/cancel": {
            "post": {
                "tags": [
                    "schedules"
                ],
                "summary": "cancel schedule",
                "operationId": "cancelSchedule",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "schedule id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/auth/schedule/{id}": {
            "get": {
                "tags": [
                    "schedules"
                ],
                "summary": "search schedule by id",
                "operationId": "searchSchedule",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "schedule id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "204": {
                        "description": "Content not found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "schedules"
                ],
                "summary": "update schedule",
                "operationId": "updateSchedule",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "schedule id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "date": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "date": "01-01-2025 15:00"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successfully updated"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "schedules"
                ],
                "summary": "remove schedule",
                "operationId": "removeSchedule",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "schedule id",
                        "required": true,
                        "schema": {
                            "type": "integer"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully deleted"
                    },
                    "204": {
                        "description": "Content not found"
                    },
                    "400": {
                        "description": "This schedule cannot be deleted as its status is no longer open"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/auth/user": {
            "get": {
                "tags": [
                    "users"
                ],
                "summary": "list all users in system",
                "operationId": "listUsers",
                "responses": {
                    "200": {
                        "description": "Validation Response"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/auth/register": {
            "post": {
                "tags": [
                    "authentication"
                ],
                "summary": "create account to access the system",
                "operationId": "create account",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "document_id": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "phone": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "name": "Roberto Augusto",
                                    "document_id": "123456789012",
                                    "email": "mail@mail.com",
                                    "phone": "(31) 91234-5678",
                                    "password": "test123"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                }
            }
        },
        "/api/auth/user/{id}": {
            "get": {
                "tags": [
                    "users"
                ],
                "summary": "list user by id",
                "operationId": "listUserById",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "user id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "204": {
                        "description": "Content not found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "users"
                ],
                "summary": "update account data",
                "operationId": "update account",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "user id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "name": {
                                        "type": "string"
                                    },
                                    "phone": {
                                        "type": "string"
                                    },
                                    "email": {
                                        "type": "string"
                                    },
                                    "password": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "name": "Roberto Augusto",
                                    "phone": "(31) 91234-5678",
                                    "email": "mail@mail.com",
                                    "password": "1234678"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successfully updated"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "users"
                ],
                "summary": "delete your account",
                "operationId": "delete account",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "user id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully deleted"
                    },
                    "204": {
                        "description": "Content not found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/auth/user/document/{document}": {
            "get": {
                "tags": [
                    "users"
                ],
                "summary": "list user by document",
                "operationId": "listUserByDocument",
                "parameters": [
                    {
                        "name": "document",
                        "in": "path",
                        "description": "user document",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "204": {
                        "description": "Content not found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/auth/user/{id}/pet": {
            "get": {
                "tags": [
                    "users"
                ],
                "summary": "list all pets of user",
                "operationId": "listPetsByUser",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "user id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "204": {
                        "description": "Content not found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/auth/vet": {
            "get": {
                "tags": [
                    "vets"
                ],
                "summary": "list all vets in system",
                "operationId": "listVets",
                "responses": {
                    "200": {
                        "description": "Validation Response"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            },
            "post": {
                "tags": [
                    "vets"
                ],
                "summary": "register user as vet",
                "operationId": "createVet",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "user_id": {
                                        "type": "integer"
                                    },
                                    "crm": {
                                        "type": "string"
                                    },
                                    "specialization": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "user_id": 1,
                                    "crm": "031237",
                                    "specialization": "Animal food"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Success"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/auth/vet/{id}": {
            "get": {
                "tags": [
                    "vets"
                ],
                "summary": "list vet by id",
                "operationId": "listVetById",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "vet id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "204": {
                        "description": "Content not found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            },
            "put": {
                "tags": [
                    "vets"
                ],
                "summary": "update vet account details",
                "operationId": "updateVet",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "vet id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "properties": {
                                    "crm": {
                                        "type": "string"
                                    },
                                    "specialization": {
                                        "type": "string"
                                    }
                                },
                                "type": "object",
                                "example": {
                                    "crm": "0123732",
                                    "specialization": "Animal food"
                                }
                            }
                        }
                    }
                },
                "responses": {
                    "200": {
                        "description": "Successfully updated"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            },
            "delete": {
                "tags": [
                    "vets"
                ],
                "summary": "remove user as vet account",
                "operationId": "removeVet",
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "vet id",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Successfully deleted"
                    },
                    "204": {
                        "description": "Content not found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        },
        "/api/auth/vet/document/{document}": {
            "get": {
                "tags": [
                    "vets"
                ],
                "summary": "list vet by CRM",
                "operationId": "listUserByCRM",
                "parameters": [
                    {
                        "name": "document",
                        "in": "path",
                        "description": "vet CRM",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success"
                    },
                    "204": {
                        "description": "Content not found"
                    }
                },
                "security": [
                    {
                        "apiAuth": []
                    }
                ]
            }
        }
    },
    "components": {
        "securitySchemes": {
            "apiAuth": {
                "type": "http",
                "description": "Login with email and password to get the authentication token",
                "name": "Token",
                "in": "header",
                "bearerFormat": "JWT",
                "scheme": "bearer"
            }
        }
    }
}